### ISSUE TITLE
We've lost a well-studied lake in recent temp pulls

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#122]
I'm only focusing on this one because it _was_ a well-studied lake that Jared was using and now it doesn't have any observations in the repo or data release. 

The lake is Found Lake in Vilas, WI and it is `nhdhr_70331799` with the most likely major data source coming from `WIDNR_WQX-643482`. That monitoring location has 1391 temperature records, but we have lost them somewhere. In the partitions, this one should be in 
```r
feather::read_feather('6_wqp_fetch/inout/wqptemp_partitions.feather') %>% filter(MonitoringLocationIdentifier == 'WIDNR_WQX-643482')
# A tibble: 1 x 4
  site_id        resultCount MonitoringLocationIdentifier PullTask   
  <chr>                <dbl> <chr>                        <chr>      
1 nhdhr_70331799        1391 WIDNR_WQX-643482             wqptemp_054
```
but I don't see it in that file ('6_wqp_fetch/tmp/wqptemp_054.rds'), and that file does have 24950 obs in it. 

I did check that I can pull data from this site and get data :+1:

I am not planning to rebuild that part of the pipeline now because of the looming WQP issues, but maybe we should? 

I'm also not sure if I am looking at locally out of date files in this `tmp` dir. Did @limnoliver build all of the temperature data on 1/13 which would include these `wqptemp_n.rds` files?

**Comment by limnoliver** [comment]
We have lost Found Lake?! ha!

I'll figure out what's going on -- I rebuilt this pipeline last, and I can see `WIDNR_WQX-643482` has 1391 records in file `6_wqp_fetch/tmp/wqptemp_054.rds`, so the data are being lost somewhere in the munge (but I don't think munge changed in the last build...).

**Comment by limnoliver** [comment]
I'm not sure what was going on _before_, but now, `WIDNR_WQX-643482` returns 1391 records, 219 of which have depth values associated with the temperature values. These 219 records with depth values also get dropped, because the depth column `ResultDepthHeightMeasure/MeasureValue` gets chosen for organization ID `WIDNR_WQX`, when the values for this particular lake are stored in `ActivityDepthHeightMeasure/MeasureValue` [here](https://github.com/USGS-R/lake-temperature-model-prep/blame/master/7a_wqp_munge/src/munge_wqp_dat.R#L21). 

One solution would be to pick depth value by MonitoringLocationIdentifier instead of OrganizationIdentifier. But, this would not fix the fact that most of these particular data are being dropped because of no depth information.

**Comment by jread-usgs** [comment]
See #175
