### ISSUE TITLE
move `gd_get` to getters.yml

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#180]
see [PR comment](https://github.com/USGS-R/lake-temperature-model-prep/pull/179/files#r502648644)

@aappling-usgs is this as simple as moving all `gd_get()` calls into that one new yaml and including that in the `remake.yml` or does this instead require replacing all the calls to `sc_retrieve` with `sc_retrieve(ind_file, remake_file = getters.yml)` and keeping the getters.yml _out_ of the remake.yml `include` field? (or some other variant)

**Comment by aappling-usgs** [comment]
The latter. But here's a trade for you: Spend 10 minutes reviewing and merging https://github.com/USGS-R/scipiper/pull/146 and then you won't have to spend 10 minutes pasting `remake_file = 'getters.yml'` in a bunch of files, because that PR makes the default for `sc_retrieve` be `remake_file='getters.yml'`.

**Comment by jread-usgs** [comment]
It's a deal!
