### ISSUE TITLE
Add Navico lakes into pipeline

### ISSUE THREAD

**Issue by hcorson-dosch** [USGS-R/lake-temperature-model-prep#207]
Gretchen forwarded data provided by Ray Valley of Navico, Inc. on 6/7/21. The attribute data are:
``` r
> colnames(navico_data)
 [1] "MapWaterbody_ID"          "WaterbodyName"            "State"                   
 [4] "County"                   "CenterLat"                "CenterLong"              
 [7] "AreaSqKm"                 "SocialMapMaxDepthMeters"  "SocialMapMeanDepthMeters"
[10] "NumberOfTrips
```

The new point dataset from Navico contains lake depth data for 826 lakes. Of those 826 lakes, we did not previously have depth data for 268. Those 268 lakes are spread across 9 states (Arkansas [17 lakes], Illinois [26], Indiana [45], Iowa [7], Michigan [94], Minnesota [31], Missouri [18], Ohio [19], and Wisconsin [11]).

I'm starting this issue to document all of the steps that need to be taken to get this new data into the pipeline, and resulting expected rebuilds:

**** STILL A WORK IN PROGRESS ****

* Add data to Drive
  - [ ] Add Navico dataset to Google Drive - `1_crosswalk_fetch/in/`
  - [ ] Add getter for Navico dataset in `getters.yml`
* Changes in `1_crosswalk_fetch.yml`
  - [ ] Add 'Arkansas' and 'Ohio' to `nhd_HR_download_plan`
  - [ ] Rebuild `1_crosswalk_fetch/out/canonical_lakes_sf.rds.ind`
  - [ ] Add 'AR' and 'OH' to states vector used to build `1_crosswalk_fetch/out/LAGOS_lakes_sf.rds.ind`
  - [ ] Rebuild `1_crosswalk_fetch/out/LAGOS_lakes_sf.rds.ind`
  - [ ] Rebuild `1_crosswalk_fetch/out/wqp_lake_temperature_sites_sf.rds.ind`
  - [ ] Rebuild `1_crosswalk_fetch/out/wqp_lake_secchi_sites_sf.rds.ind`
* Changes in `2_crosswalk_munge`
  - [ ] Create NHD_Navico crosswalk ind file
  - [ ] Add crosswalk to `gettters.yml` as `2_crosswalk_munge/out/` file
  - [ ] Rebuild `2_crosswalk_munge/out/wqptemp_nhdhr_xwalk.rds.ind`
  - [ ] Rebuild `2_crosswalk_munge/out/wqpsecchi_nhdhr_xwalk.rds.ind`
  - [ ] Rebuild `2_crosswalk_munge/out/buffered_lakes_sf.rds.ind`
  - [ ] Rebuild `2_crosswalk_munge/out/centroid_lakes_sf.rds.ind`
* Changes to `3_params_fetch.yml`
  - None? Since bringing depth data in along with point data when it's first fetched?
* Changes to `4_params_munge`
  - [ ] Munge Navico depth data using NHD_Navico crosswalk - make new `4_params_munge/out/` ind file
  - [ ] Add munged data ind file to `getters.yml`
* Changes to `6_drivers_fetch.yml`
  - None? Since note about not yet expanding drivers?
* Changes to `6_nwis_fetch.yml`
  - None, since just for limited reservoir data at the moment
* Changes to `6_temp_coop_fetch.yml`
  - None, since no new temp data here
* Changes to `6_wqp_fetch.yml`
  - [ ] Rebuild `6_wqp_fetch/out/wqp_temperature_data.rds.ind`
  - [ ] Rebuild `6_wqp_fetch/out/wqp_secchi_data.rds.ind`
* Changes to `7_drivers_munge.yml`
  - None
* Changes to `7_config_merge.yml`
  - [ ] Add new Navico munged depth data in `4_params_munge/out/` to argument list for `7_config_merge/out/nml_H_A_values.rds.ind`
  - [ ] Rebuild ` 7_config_merge/out/nml_lake_depth_values.rds.ind`
  - [ ] Rebuild `7_config_merge/out/nml_layer_thick_values.rds.ind`
  - [ ] Rebuild `7_config_merge/out/nml_meteo_fl_values.rds.ind`
  - [ ] Rebuild `7_config_merge/out/nml_Kw_values.rds.ind` (b/c of rebuilds in `7a_wqp_munge.yml`)
  - [ ] Rebuild `7_config_merge/out/nml_list.rds.ind`
* Changes to `7a_temp_coop_munge.yml`
  - None
* Changes to `7a_wqp_munge.yml`
  - [ ] Rebuild `7a_wqp_munge/out/temp_wqp_munged.feather.ind`
  - [ ] Rebuild `7a_wqp_munge/out/secchi_wqp_munged.feather.ind`
  - [ ] Rebuild `7a_wqp_munge/out/temp_wqp_munged_linked.feather.ind`
  - [ ] Rebuild `7a_wqp_munge/out/secchi_wqp_munged_linked.feather.ind`
* Changes to `7a_nwis_munge.yml`
  - None b/c all limited reservoir data for now
* Changes to `7b_temp_merge.yml`
  - [ ] Rebuild `7b_temp_merge/out/merged_temp_data_alltimes.feather.ind`
  - [ ] Rebuild `7b_temp_merge/out/merged_temp_data_daily.feather.ind`
  - [ ] Rebuild `7b_temp_merge/out/temp_data_with_sources.feather.ind`
  - [ ] Rebuild `7b_temp_merge/out/source_metadata_for_release.csv.ind`
* Changes to `8_viz.yml`
  - [ ] Rebuild `8_viz/out/lake_obs_counts.png`
  - [ ] Rebuild `8_viz/inout/lakes_summary.feather.ind`
  - [ ] Rebuild `8_viz/out/lakes_summary_fig.html.ind`

**Comment by jread-usgs** [comment]
Hayley - I think I normally approach this a little differently by allowing the pipeline tools to tell me what needs to be build instead of documenting what the builds are expected to be. But it is helpful to list out the expected changes like you've done here (just don't be surprised if the build flows disagree with you in some spots :) )

I think you've got most of the steps in here. 

I am a little out of practice on these, but I think you don't actually create a target in the recipes for `1_crosswalk` and you instead add the raw file name to the `getters.yml` and run `scipiper::gd_confirm_posted()` on the raw file (with the .ind extension added) that you will put in the gdrive location for `1_crosswalk/in/{name_here.csv.ind}`. Running this will create the .ind file and also the build file that both get checked into git. 

Then you'd create your explicit xwalk target in [`2_crosswalk_munge`](https://github.com/USGS-R/lake-temperature-model-prep/blob/master/2_crosswalk_munge.yml) using either a custom function like [this](https://github.com/USGS-R/lake-temperature-model-prep/blob/master/2_crosswalk_munge.yml#L130) or by creating an intermediate sf_point.ind target that could be used as input to the more generic `crosswalk_points_in_poly` function like [this](https://github.com/USGS-R/lake-temperature-model-prep/blob/master/2_crosswalk_munge.yml#L118)

Then I think you might need to write a custom function for grabbing your `1_crosswalk/in/{name_here.csv.ind}` and your xwalk.ind file to match depths with `site_id` like [this](https://github.com/USGS-R/lake-temperature-model-prep/blob/master/4_params_munge.yml#L74)

After this I think you just need to slot in your indicator filename into the depth/heigh/area config function [here](https://github.com/USGS-R/lake-temperature-model-prep/blob/master/7_config_merge.yml#L58). Order matters, so we put the sources we have higher confidence ahead of those we have less confidence in. Since these Navico-supplied max depth points are from bathymetric maps, I'd put higher confidence on them than the other depth-only sources, so I'd suggest you make this the first of the `depth` args that goes in. Keep in mind this function looks for `depth` in the file name and treats those differently than inputs with `bathy`, so your `4_params_munge/out/{target_name}.ind` will need to include `depth` in the target_name. 

Lastly, `which_dirty('8_viz')` will give you a heads up on expected and unexpected changes, and if there aren't show-stoppers in there, `scmake('8_viz')` should complete all of the needed builds. 

Note that I'm leaving out the expansion to OH and AR for this. I don't think we need to go there...yet...for this project.

**Comment by hcorson-dosch** [comment]
Ok updated plan:

* Add data to Drive
  - [ ] Add Navico dataset to Google Drive - `1_crosswalk_fetch/in/`
  - [ ] Add getter for Navico dataset in `getters.yml`
  - [ ] Run `scipiper::gd_confirm_posted()` on the raw file (with `.ind` extension)
* Changes in `1_crosswalk_fetch.yml`
  - None
* Changes in `2_crosswalk_munge`
  - [ ] Create NHD_Navico crosswalk ind file
  - [ ] Add crosswalk to `gettters.yml` as `2_crosswalk_munge/out/` file
* Changes to `3_params_fetch.yml`
  - None? Since bringing depth data in along with point data when it's first fetched?
* Changes to `4_params_munge`
  - [ ] Munge Navico depth data using NHD_Navico crosswalk - make new `4_params_munge/out/` ind file -- use 'depth' in the target name
  - [ ] Add munged data ind file to `getters.yml`
* Changes to `6_drivers_fetch.yml`
  - None? Since note about not yet expanding drivers?
* Changes to `6_nwis_fetch.yml`
  - None, since just for limited reservoir data at the moment
* Changes to `6_temp_coop_fetch.yml`
  - None, since no new temp data here
* Changes to `6_wqp_fetch.yml`
  - None
* Changes to `7_drivers_munge.yml`
  - None
* Changes to `7_config_merge.yml`
  - [ ] Add new Navico munged depth data in `4_params_munge/out/` to argument list for `7_config_merge/out/nml_H_A_values.rds.ind` - make first of 'depth' args
* Changes to `7a_temp_coop_munge.yml`
  - None
* Changes to `7a_wqp_munge.yml`
  - None
* Changes to `7a_nwis_munge.yml`
  - None b/c all limited reservoir data for now
* Changes to `7b_temp_merge.yml`
  - None
* Changes to `8_viz.yml`
  - None - `scmake('8_viz')` should complete all needed builds

**Comment by jread-usgs** [comment]
looks right to me

**Comment by hcorson-dosch** [comment]
I think I may actually need a `1_crosswalk_fetch/out` target in `1_crosswalk_fetch.yml `to go from `Navico_lakes_depths.csv` (the file I'm dropping into google drive in the `1_crosswalk/fetch/in` folder) to `Navico_lakes_depths_sf.rds.ind`, right? B/c when I get to the `2_crosswalk_munge` step I'll need a sf points dataframe to compare w/ `1_crosswalk_fetch/out/canonical_lakes_sf.rds.ind` right?

**Comment by jread-usgs** [comment]
I think you can do it either way - by creating an intermediate .rds target, or accepting that .ind directly into a custom function. This is the part I was referring to above with 

> Then you'd create your explicit xwalk target in 2_crosswalk_munge using either a custom function like this or by creating an intermediate sf_point.ind target that could be used as input to the more generic crosswalk_points_in_poly function like this

**Comment by hcorson-dosch** [comment]
Ah, I see. Thanks!

**Comment by hcorson-dosch** [comment]
Started w/ 826 Navico lakes. 

When completed xwalk with nhdhr, dropped to 697 (probably b/c we're not yet adding AR and OH, and may have been some points that didn't match to nhdhr polygons)

When munged depth data, dropped to 694, b/c filtered out sites where max reported Navico depth = NA
