### ISSUE TITLE
Make the GCM grid in R

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temperature-model-prep#236]
Currently, our workflow used @hcorson-dosch's robust Python Notebook to generate the appropriate grid cell spatial files from the GCM grid on GDP. We want to avoid mixing and matching languages within this pipeline so that we don't introduce brittleness with environment setup. So, in #233, we just committed the resulting shapefiles and the Python notebook (`7_drivers_munge/in/Reconstruct_GCM_grid.ipynb`) that created them. 

This issue should try to use `st_make_grid()` to reconstruct the grid, as [this example](https://github.com/USGS-R/lake-surface-temperature-prep/blob/main/4_drivers_fetch/src/grid_utils.R#L13) does. If that doesn't work, we can build a multipolygon sf object instead (see [this comment](https://github.com/USGS-R/lake-temperature-model-prep/pull/233#issuecomment-984062211)). Once the new grid is built, we will no longer be relying on anything from the Python workflow and we can delete `7_drivers_munge/in/Reconstruct_GCM_grid.ipynb`.

**Comment by hcorson-dosch** [comment]
I've got this workflow set up and running [here](https://github.com/hcorson-dosch/lake-temperature-model-prep/blob/gcm_driver_data_munge_pipeline/_targets.R#L23-L33), but once GDP is back online, we will need to add a target to directly download the netcdf file we're using to reconstruct the grid, instead of loading it in manually. Using `sf_make_grid()` does work, so long as you use the custom lambert conformal conic projection defined in the netCDF and set the offset using the projected coordinates from the netCDF.

**Comment by jread-usgs** [comment]
Two thoughts here, since I hope it isn't needed to download the whole file locally to extract the metadata: 
- you can often reach NetCDF metadata (such as the spatial metadata you need to get the grid right) via the web without downloading the file. This is likely possible here when thredds is back online
- If you'd have to download the file to use it, you could 1) use the OPeNDAP subset algorithm (Lindsay used this for hurricane gifs) to just grab the entire spatial domain of the file, but only one timestep, making the file small, 2) instead consider hard-coding the projection and offset as variables. I am bringing up option 2 here because having a local file meant to represent the contents of a remote file can be error-prone (e.g., if the remote file changes projection due to being repacked/reprojected and/or optimized in some other way, we wouldn't know and would treat it the same if rebuilding the GCM targets) and hard-coding the information is likely about the same risk but is simpler.

**Comment by lindsayplatt** [comment]
Closed by #238. Ended up implementing a short `tibble` target with the 6 configs needed to reconstruct the grid rather than pulling down from GDP.
