### ISSUE TITLE
Filter incoming lakes to pull GCM data to NML lakes?

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temperature-model-prep#265]
Use NML lakes? See how many lakes are just in MN vs in MN & in NML list (see `'7_config_merge/out/nml_list.rds.ind'`)

**Comment by lindsayplatt** [comment]
Doing this comparison reveals that we would not change the number of queries to GDP that we are making (since NML lakes appear in every tile), but we would change the number of cells called per query, which would impact download times. This would really help a few of the tiles, but not all. 

In map: black squares = the query tiles, light purple squares = cells for all MN lakes, and dark purple = cells for MN lakes + NML

![image](https://user-images.githubusercontent.com/13220910/149368088-e7b695da-0f00-4a0c-b282-131c8d41b4f1.png)

```r
# Making the map (when my targets pipeline was set up for ALL of MN)

library(targets)
library(scipiper)
library(sf)
library()

nml <- readRDS(sc_retrieve('7_config_merge/out/nml_list.rds.ind'))

tar_load(lake_cell_xwalk_df)
tar_load(grid_cells_sf)
tar_load(query_tiles)
tar_load(grid_tiles_sf)

# All MN Lake cells
mn_all_cells <- lake_cell_xwalk_df %>% pull(cell_no) %>% unique()

# Just NML ones
mn_nml_cells <- lake_cell_xwalk_df %>% 
  filter(site_id %in% names(nml)) %>% 
  pull(cell_no) %>% unique()

mn_grid_tiles_sf <- grid_tiles_sf %>% filter(tile_no %in% query_tiles)
mn_grid_cells <- grid_cells_sf %>% filter(cell_no %in% mn_all_cells) 
mn_nml_grid_cells <- grid_cells_sf %>% filter(cell_no %in% mn_nml_cells) 

ggplot() + 
  geom_sf(data = mn_grid_cells, fill = "plum3") +
  geom_sf(data = mn_nml_grid_cells, fill = "purple3") +
  geom_sf(data = mn_grid_tiles_sf, fill = NA, size = 2)
```

**Comment by hcorson-dosch** [comment]
Hmm. I think either approach could work fine. Given that a) it's not a substantial reduction in tiles, and only a big reduction in # of cells in 2 tiles, and b) like you noted, we may later use this driver data for purposes other than glm modeling, I'm leaning towards keeping this filtering step [in the `lake-temperature-process-models` pipeline](https://github.com/USGS-R/lake-temperature-process-models/blob/main/1_prep.R#L15-L18). I think it's more logical to make a glm-specific filtering step in that pipeline than in this one. The downside is that we'd end up [transferring more data to Caldera](https://github.com/USGS-R/lake-temperature-process-models/issues/4) than we'd need for the glm modeling alone, BUT it think it's possible that we'd want that data there for future ML projections work. Also, particularly once we scale up to the full footprint, there's always the possibility that the addition of new data would make lakes already in our pipeline newly GLM-modelable. In that event, it would be better to have to only update the `nml_list.rds`, rather than redo the whole download.

**Comment by lindsayplatt** [comment]
I don't think there is an inevitability that we will do projections beyond using GLM any time soon, but it would be nice to leave that option open + it wouldn't be a drastic change in the query times now + keeping GLM-specific filtering in the GLM pipeline would help keep our repos organized. OK, closing this and carrying on without the NML filter here.
