### ISSUE TITLE
Questions Kelsey has about data prep

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/lake-temperature-model-prep#57]
1. How does GLM handle leap years? That is, does she need clarity estimates for each day? Or is it ok if she's missing the leap year day?

2. How do we make sure that large lakes that got dropped in the Winslow effort don't get dropped when we switch to NHD high-res? And, can we write a test for "priority lakes" that checks specifically for lakes of interest to be sure they made it through the pipeline?

3. Should Kelsey limit her time-varying clarity model to only lakes that we are modeling for temperature? E.g., small lakes are dropped in our efforts, should these be dropped in her model as well? Or fit separately? 

4. How is bathymetry handled when there are multiple sub-basins (polygons) for an individual lake? This goes both ways: if the bathy data is in two basins, and NHD is one basin, how do you combine? If bathy is for whole lake, but NHD has two basins, how to split?

**Comment by jread-usgs** [comment]
> How does GLM handle leap years? That is, does she need clarity estimates for each day? Or is it ok if she's missing the leap year day?

yes, GLM does include leap year days, so the timeseries of clarity would need to include that day (or simply interpolate on leap years to generate the timeseries)

> How do we make sure that large lakes that got dropped in the Winslow effort don't get dropped when we switch to NHD high-res? And, can we write a test for "priority lakes" that checks specifically for lakes of interest to be sure they made it through the pipeline?

I expect continuing to write summary targets that are specific to project needs (e.g., tables or maps) will be the best way to make sure we aren't losing key lakes. 

> Should Kelsey limit her time-varying clarity model to only lakes that we are modeling for temperature? E.g., small lakes are dropped in our efforts, should these be dropped in her model as well? Or fit separately?

We didn't originally drop small lakes because they were small, we dropped them because they weren't managed for fisheries. If they are relevant for management questions and we have key info for them (e.g., depth and clarity) I'd expect we'd want to include them. PS, I ❤️ small lakes. 

> How is bathymetry handled when there are multiple sub-basins (polygons) for an individual lake? This goes both ways: if the bathy data is in two basins, and NHD is one basin, how do you combine? If bathy is for whole lake, but NHD has two basins, how to split?

I think the easier part is combining, since we'd just add the two hysographic curves together. If we need to split but the bathy data isn't resolved that that level, we'd either need to make assumptions or go digging for a bathy source that we could digitize or process in a way to resolve the basins individually. That effort can be laborious and I'd prefer our group avoid it (e.g., tracing bathy contours and calculating areas..)

**Comment by jread-usgs** [comment]
I think we've covered these things or they are still being discussed in a different forum (the multi-basin question)
